<template>
  <!-- Button trigger modal -->
  <div class="float-end mb-3">
    <button
      type="button"
      class="btn btn-primary"
      data-bs-toggle="modal"
      data-bs-target="#exampleAddPropertyModal"
    >
      <span class="material-symbols-outlined icon-align"> add </span>
      Add Property
    </button>
  </div>

  <!-- Modal -->
  <div
    class="modal fade"
    id="exampleAddPropertyModal"
    tabindex="-1"
    aria-labelledby="exampleAddPropertyModalLabel"
    aria-hidden="true"
  >
    <!-- Vertically centered scrollable modal -->
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalAddPropertyLabel">
            Add Property
          </h5>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <form id="addPropertyForm">
            <div class="mb-3">
              <label for="exampleSelectPropertyType1" class="form-label"
                >Property Type (Owner/Rental)</label
              >
              <select
                id="exampleSelectPropertyType1"
                class="form-select"
                aria-label="Default select example"
                v-model="PropertyType"
              >
                <option value="" hidden>Select your option</option>
                <option value="0">Owner Occupied</option>
                <option value="1">Rental/Investment</option>
              </select>
            </div>
            <div class="mb-3">
              <label for="exampleInputPostalCode1" class="form-label"
                >Postal Code</label
              >
              <input
                type="number"
                class="form-control"
                id="exampleInputPostalCode1"
                @change="retrieveAddress"
                placeholder="Postal Code"
              />
            </div>
            <div class="mb-3">
              <label for="exampleInputFullAddress1" class="form-label"
                >Full Address</label
              >
              <input
                type="text"
                class="form-control"
                id="exampleInputFullAddress1"
                placeholder="Address (Note: Autogenerated from Postal Code)"
              />
            </div>
            <label for="exampleInputUnitNumber1" class="form-label"
              >Unit Number</label
            >
            <div class="input-group mb-3">
              <span class="input-group-text">#</span>

              <input
                type="text"
                class="form-control"
                id="exampleInputUnitNumber1"
                placeholder="Unit Number "
              />
            </div>

            <label for="exampleInputPurchasePrice1" class="form-label"
              >Purchase Price</label
            >
            <div class="input-group mb-3">
              <span class="input-group-text">$</span>
              <input
                type="number"
                class="form-control"
                id="exampleInputPurchasePrice1"
                placeholder="Purchase Price"
              />
            </div>

            <label for="exampleInputUpfrontPayment1" class="form-label"
              >Upfront Payment</label
            >
            <div class="input-group mb-4">
              <span class="input-group-text">$</span>
              <input
                type="text"
                class="form-control"
                id="exampleInputUpfrontPayment1"
                placeholder="Upfront Payment"
              />
            </div>

            <div v-if="PropertyType === '1'">
              <hr />
              <!-- Start::Tenant 1-->
              <h5 class="text-left fw-bold">Tenant Number: 1</h5>
              <div class="mb-3">
                <div class="row">
                  <div class="col">
                    <label for="exampleInputFirstName1" class="form-label"
                      >First Name</label
                    >
                    <input
                      type="text"
                      class="form-control"
                      id="exampleInputFirstName1"
                      name="firstName"
                      placeholder="First name"
                      required
                    />
                  </div>

                  <div class="col">
                    <label for="exampleInputLastName1" class="form-label"
                      >Last Name</label
                    >
                    <input
                      type="text"
                      class="form-control"
                      id="exampleInputLastName1"
                      name="lastName"
                      placeholder="Last name"
                      required
                    />
                  </div>
                </div>
              </div>

              <div class="mb-3">
                <div class="row">
                  <div class="col">
                    <label for="exampleInputContractStart1" class="form-label"
                      >Contract Start Date</label
                    >
                    <input
                      type="date"
                      class="form-control"
                      id="exampleInputContractStart1"
                      name="contractStart"
                      required
                    />
                  </div>

                  <div class="col">
                    <label for="exampleInputContractEnd1" class="form-label"
                      >Contract End Date</label
                    >
                    <input
                      type="date"
                      class="form-control"
                      id="exampleInputContractEnd1"
                      name="contractEnd"
                      required
                    />
                  </div>
                </div>
              </div>

              <label for="exampleMonthlyRent1" class="form-label"
                >Monthly Rent</label
              >
              <div class="input-group mb-3">
                <span class="input-group-text">$</span>
                <input
                  type="number"
                  class="form-control"
                  id="exampleMonthlyRent1"
                />
              </div>
              <!-- End::Tenant 1-->

              <!-- Start::Tenant 2-->
              <h5 class="text-left fw-bold">Tenant Number: 2</h5>
              <div class="mb-3">
                <div class="row">
                  <div class="col">
                    <label for="exampleInputFirstName2" class="form-label"
                      >First Name</label
                    >
                    <input
                      type="text"
                      class="form-control"
                      id="exampleInputFirstName2"
                      name="firstName"
                      placeholder="First name"
                      required
                    />
                  </div>

                  <div class="col">
                    <label for="exampleInputLastName2" class="form-label"
                      >Last Name</label
                    >
                    <input
                      type="text"
                      class="form-control"
                      id="exampleInputLastName2"
                      name="lastName"
                      placeholder="Last name"
                      required
                    />
                  </div>
                </div>
              </div>

              <div class="mb-3">
                <div class="row">
                  <div class="col">
                    <label for="exampleInputContractStart2" class="form-label"
                      >Contract Start Date</label
                    >
                    <input
                      type="date"
                      class="form-control"
                      id="exampleInputContractStart2"
                      name="contractStart"
                      required
                    />
                  </div>

                  <div class="col">
                    <label for="exampleInputContractEnd2" class="form-label"
                      >Contract End Date</label
                    >
                    <input
                      type="date"
                      class="form-control"
                      id="exampleInputContractEnd2"
                      name="contractEnd"
                      required
                    />
                  </div>
                </div>
              </div>

              <label for="exampleMonthlyRent2" class="form-label"
                >Monthly Rent</label
              >
              <div class="input-group mb-3">
                <span class="input-group-text">$</span>
                <input
                  type="number"
                  class="form-control"
                  id="exampleMonthlyRent2"
                />
              </div>
              <!-- End::Tenant 2-->

              <!-- Start::Tenant 3-->
              <h5 class="text-left fw-bold">Tenant Number: 3</h5>
              <div class="mb-3">
                <div class="row">
                  <div class="col">
                    <label for="exampleInputFirstName3" class="form-label"
                      >First Name</label
                    >
                    <input
                      type="text"
                      class="form-control"
                      id="exampleInputFirstName3"
                      name="firstName"
                      placeholder="First name"
                      required
                    />
                  </div>

                  <div class="col">
                    <label for="exampleInputLastName3" class="form-label"
                      >Last Name</label
                    >
                    <input
                      type="text"
                      class="form-control"
                      id="exampleInputLastName3"
                      name="lastName"
                      placeholder="Last name"
                      required
                    />
                  </div>
                </div>
              </div>

              <div class="mb-3">
                <div class="row">
                  <div class="col">
                    <label for="exampleInputContractStart3" class="form-label"
                      >Contract Start Date</label
                    >
                    <input
                      type="date"
                      class="form-control"
                      id="exampleInputContractStart3"
                      name="contractStart"
                      required
                    />
                  </div>

                  <div class="col">
                    <label for="exampleInputContractEnd3" class="form-label"
                      >Contract End Date</label
                    >
                    <input
                      type="date"
                      class="form-control"
                      id="exampleInputContractEnd3"
                      name="contractEnd"
                      required
                    />
                  </div>
                </div>
              </div>

              <label for="exampleMonthlyRent3" class="form-label"
                >Monthly Rent</label
              >
              <div class="input-group mb-3">
                <span class="input-group-text">$</span>
                <input
                  type="number"
                  class="form-control"
                  id="exampleMonthlyRent3"
                />
              </div>
              <!-- End::Tenant 3-->

              <!-- Start::Tenant 4-->
              <h5 class="text-left fw-bold">Tenant Number: 4</h5>
              <div class="mb-3">
                <div class="row">
                  <div class="col">
                    <label for="exampleInputFirstName4" class="form-label"
                      >First Name</label
                    >
                    <input
                      type="text"
                      class="form-control"
                      id="exampleInputFirstName4"
                      name="firstName"
                      placeholder="First name"
                      required
                    />
                  </div>

                  <div class="col">
                    <label for="exampleInputLastName4" class="form-label"
                      >Last Name</label
                    >
                    <input
                      type="text"
                      class="form-control"
                      id="exampleInputLastName4"
                      name="lastName"
                      placeholder="Last name"
                      required
                    />
                  </div>
                </div>
              </div>

              <div class="mb-3">
                <div class="row">
                  <div class="col">
                    <label for="exampleInputContractStart4" class="form-label"
                      >Contract Start Date</label
                    >
                    <input
                      type="date"
                      class="form-control"
                      id="exampleInputContractStart4"
                      name="contractStart"
                      required
                    />
                  </div>

                  <div class="col">
                    <label for="exampleInputContractEnd4" class="form-label"
                      >Contract End Date</label
                    >
                    <input
                      type="date"
                      class="form-control"
                      id="exampleInputContractEnd4"
                      name="contractEnd"
                      required
                    />
                  </div>
                </div>
              </div>

              <label for="exampleMonthlyRent4" class="form-label"
                >Monthly Rent</label
              >
              <div class="input-group mb-3">
                <span class="input-group-text">$</span>
                <input
                  type="number"
                  class="form-control"
                  id="exampleMonthlyRent4"
                />
              </div>
              <!-- End::Tenant 4-->

              <!-- Start::Tenant 5-->
              <h5 class="text-left fw-bold">Tenant Number: 5</h5>
              <div class="mb-3">
                <div class="row">
                  <div class="col">
                    <label for="exampleInputFirstName5" class="form-label"
                      >First Name</label
                    >
                    <input
                      type="text"
                      class="form-control"
                      id="exampleInputFirstName5"
                      name="firstName"
                      placeholder="First name"
                      required
                    />
                  </div>

                  <div class="col">
                    <label for="exampleInputLastName5" class="form-label"
                      >Last Name</label
                    >
                    <input
                      type="text"
                      class="form-control"
                      id="exampleInputLastName5"
                      name="lastName"
                      placeholder="Last name"
                      required
                    />
                  </div>
                </div>
              </div>

              <div class="mb-3">
                <div class="row">
                  <div class="col">
                    <label for="exampleInputContractStart5" class="form-label"
                      >Contract Start Date</label
                    >
                    <input
                      type="date"
                      class="form-control"
                      id="exampleInputContractStart5"
                      name="contractStart"
                      required
                    />
                  </div>

                  <div class="col">
                    <label for="exampleInputContractEnd5" class="form-label"
                      >Contract End Date</label
                    >
                    <input
                      type="date"
                      class="form-control"
                      id="exampleInputContractEnd5"
                      name="contractEnd"
                      required
                    />
                  </div>
                </div>
              </div>

              <label for="exampleMonthlyRent5" class="form-label"
                >Monthly Rent</label
              >
              <div class="input-group mb-3">
                <span class="input-group-text">$</span>
                <input
                  type="number"
                  class="form-control"
                  id="exampleMonthlyRent5"
                />
              </div>
              <!-- End::Tenant 5-->

              <!-- Start::Tenant 6-->
              <h5 class="text-left fw-bold">Tenant Number: 6</h5>
              <div class="mb-3">
                <div class="row">
                  <div class="col">
                    <label for="exampleInputFirstName6" class="form-label"
                      >First Name</label
                    >
                    <input
                      type="text"
                      class="form-control"
                      id="exampleInputFirstName6"
                      name="firstName"
                      placeholder="First name"
                      required
                    />
                  </div>

                  <div class="col">
                    <label for="exampleInputLastName6" class="form-label"
                      >Last Name</label
                    >
                    <input
                      type="text"
                      class="form-control"
                      id="exampleInputLastName6"
                      name="lastName"
                      placeholder="Last name"
                      required
                    />
                  </div>
                </div>
              </div>

              <div class="mb-3">
                <div class="row">
                  <div class="col">
                    <label for="exampleInputContractStart6" class="form-label"
                      >Contract Start Date</label
                    >
                    <input
                      type="date"
                      class="form-control"
                      id="exampleInputContractStart6"
                      name="contractStart"
                      required
                    />
                  </div>

                  <div class="col">
                    <label for="exampleInputContractEnd6" class="form-label"
                      >Contract End Date</label
                    >
                    <input
                      type="date"
                      class="form-control"
                      id="exampleInputContractEnd6"
                      name="contractEnd"
                      required
                    />
                  </div>
                </div>
              </div>

              <label for="exampleMonthlyRent6" class="form-label"
                >Monthly Rent</label
              >
              <div class="input-group mb-3">
                <span class="input-group-text">$</span>
                <input
                  type="number"
                  class="form-control"
                  id="exampleMonthlyRent6"
                />
              </div>
              <!-- End::Tenant 6-->
            </div>

            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-secondary"
                data-bs-dismiss="modal"
              >
                Close
              </button>
              <button
                type="button"
                v-on:click="addPropertyToServer()"
                class="btn btn-primary"
              >
                Confirm
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { auth, db } from "../firebase.js";
import { doc, setDoc, writeBatch, serverTimestamp } from "firebase/firestore";

export default {
  data() {
    return {
      PropertyType: "",
    };
  },
  emits: ["addedProperty"],
  methods: {
    async addPropertyToServer() {
      let propertyType = document.getElementById(
        "exampleSelectPropertyType1"
      ).value;
      let postalCode = document.getElementById("exampleInputPostalCode1").value;
      let fullAddress = document.getElementById(
        "exampleInputFullAddress1"
      ).value;
      let unitNumber = document.getElementById("exampleInputUnitNumber1").value;
      let purchasePrice = document.getElementById(
        "exampleInputPurchasePrice1"
      ).value;
      let upfrontPayment = document.getElementById(
        "exampleInputUpfrontPayment1"
      ).value;

      //   console.log(
      //     propertyType,
      //     postalCode,
      //     fullAddress,
      //     unitNumber,
      //     purchasePrice,
      //     upfrontPayment
      //   );

      this.$swal.fire({
        icon: "success",
        title: "Congratulations!",
        text: "You have added a new property to your collection",
        confirmButtonColor: "#0d6efd",
      });

      try {
        const docRef1 = await setDoc(
          doc(db, "Property", fullAddress + " #" + unitNumber),
          {
            isOwnerOccupied: propertyType,
            address: fullAddress,
            unitNumber: unitNumber,
            postalCode: postalCode,
            purchasePrice: purchasePrice,
            upfrontPayment: upfrontPayment,
            userId: auth.currentUser.uid,
            timestamp: serverTimestamp(),
          }
        );
        console.log(docRef1);

        if (propertyType == "1") {
          //Tenant 1 Details
          let firstName1 = document.getElementById(
            "exampleInputFirstName1"
          ).value;
          let lastName1 = document.getElementById(
            "exampleInputLastName1"
          ).value;
          let contractStart1 = document.getElementById(
            "exampleInputContractStart1"
          ).value;
          let contractEnd1 = document.getElementById(
            "exampleInputContractEnd1"
          ).value;
          let monthlyRent1 = document.getElementById(
            "exampleMonthlyRent1"
          ).value;
          //Tenant 2 Details
          let firstName2 = document.getElementById(
            "exampleInputFirstName2"
          ).value;
          let lastName2 = document.getElementById(
            "exampleInputLastName2"
          ).value;
          let contractStart2 = document.getElementById(
            "exampleInputContractStart2"
          ).value;
          let contractEnd2 = document.getElementById(
            "exampleInputContractEnd2"
          ).value;
          let monthlyRent2 = document.getElementById(
            "exampleMonthlyRent2"
          ).value;
          //Tenant 3 Details
          let firstName3 = document.getElementById(
            "exampleInputFirstName3"
          ).value;
          let lastName3 = document.getElementById(
            "exampleInputLastName3"
          ).value;
          let contractStart3 = document.getElementById(
            "exampleInputContractStart3"
          ).value;
          let contractEnd3 = document.getElementById(
            "exampleInputContractEnd3"
          ).value;
          let monthlyRent3 = document.getElementById(
            "exampleMonthlyRent3"
          ).value;
          //Tenant 4 Details
          let firstName4 = document.getElementById(
            "exampleInputFirstName4"
          ).value;
          let lastName4 = document.getElementById(
            "exampleInputLastName4"
          ).value;
          let contractStart4 = document.getElementById(
            "exampleInputContractStart4"
          ).value;
          let contractEnd4 = document.getElementById(
            "exampleInputContractEnd4"
          ).value;
          let monthlyRent4 = document.getElementById(
            "exampleMonthlyRent4"
          ).value;
          //Tenant 5 Details
          let firstName5 = document.getElementById(
            "exampleInputFirstName5"
          ).value;
          let lastName5 = document.getElementById(
            "exampleInputLastName5"
          ).value;
          let contractStart5 = document.getElementById(
            "exampleInputContractStart5"
          ).value;
          let contractEnd5 = document.getElementById(
            "exampleInputContractEnd5"
          ).value;
          let monthlyRent5 = document.getElementById(
            "exampleMonthlyRent5"
          ).value;
          //Tenant 6 Details
          let firstName6 = document.getElementById(
            "exampleInputFirstName6"
          ).value;
          let lastName6 = document.getElementById(
            "exampleInputLastName6"
          ).value;
          let contractStart6 = document.getElementById(
            "exampleInputContractStart6"
          ).value;
          let contractEnd6 = document.getElementById(
            "exampleInputContractEnd6"
          ).value;
          let monthlyRent6 = document.getElementById(
            "exampleMonthlyRent6"
          ).value;

          //   console.log(
          //     firstName1,
          //     lastName1,
          //     contractStart1,
          //     contractEnd1,
          //     monthlyRent1
          //   );
          //   console.log(
          //     firstName2,
          //     lastName2,
          //     contractStart2,
          //     contractEnd2,
          //     monthlyRent2
          //   );
          //   console.log(
          //     firstName3,
          //     lastName3,
          //     contractStart3,
          //     contractEnd3,
          //     monthlyRent3
          //   );
          //   console.log(
          //     firstName4,
          //     lastName4,
          //     contractStart4,
          //     contractEnd4,
          //     monthlyRent4
          //   );
          //   console.log(
          //     firstName5,
          //     lastName5,
          //     contractStart5,
          //     contractEnd5,
          //     monthlyRent5
          //   );
          //   console.log(
          //     firstName6,
          //     lastName6,
          //     contractStart6,
          //     contractEnd6,
          //     monthlyRent6
          //   );

          try {
            const batch = writeBatch(db);

            // Assuming you have an array of documents to add
            const documentsToAdd = [
              {
                tenantNumber: 1,
                firstName: firstName1,
                lastName: lastName1,
                contractStartDate: contractStart1,
                contractEndDate: contractEnd1,
                monthlyRent: monthlyRent1,
                unpaidMonths: this.monthDiff(contractStart1, contractEnd1),
                nextPaymentDate: this.nextPaymentDate(
                  contractStart1,
                  this.monthDiff(contractStart1, contractEnd1),
                  this.monthDiff(contractStart1, contractEnd1)
                ),
                propertyId: fullAddress + " #" + unitNumber,
                userId: auth.currentUser.uid,
                timestamp: serverTimestamp(),
              },
              {
                tenantNumber: 2,
                firstName: firstName2,
                lastName: lastName2,
                contractStartDate: contractStart2,
                contractEndDate: contractEnd2,
                monthlyRent: monthlyRent2,
                unpaidMonths: this.monthDiff(contractStart2, contractEnd2),
                nextPaymentDate: this.nextPaymentDate(
                  contractStart2,
                  this.monthDiff(contractStart2, contractEnd2),
                  this.monthDiff(contractStart2, contractEnd2)
                ),
                propertyId: fullAddress + " #" + unitNumber,
                userId: auth.currentUser.uid,
                timestamp: serverTimestamp(),
              },
              {
                tenantNumber: 3,
                firstName: firstName3,
                lastName: lastName3,
                contractStartDate: contractStart3,
                contractEndDate: contractEnd3,
                monthlyRent: monthlyRent3,
                unpaidMonths: this.monthDiff(contractStart3, contractEnd3),
                nextPaymentDate: this.nextPaymentDate(
                  contractStart3,
                  this.monthDiff(contractStart3, contractEnd3),
                  this.monthDiff(contractStart3, contractEnd3)
                ),
                propertyId: fullAddress + " #" + unitNumber,
                userId: auth.currentUser.uid,
                timestamp: serverTimestamp(),
              },
              {
                tenantNumber: 4,
                firstName: firstName4,
                lastName: lastName4,
                contractStartDate: contractStart4,
                contractEndDate: contractEnd4,
                monthlyRent: monthlyRent4,
                unpaidMonths: this.monthDiff(contractStart4, contractEnd4),
                nextPaymentDate: this.nextPaymentDate(
                  contractStart4,
                  this.monthDiff(contractStart4, contractEnd4),
                  this.monthDiff(contractStart4, contractEnd4)
                ),
                propertyId: fullAddress + " #" + unitNumber,
                userId: auth.currentUser.uid,
                timestamp: serverTimestamp(),
              },
              {
                tenantNumber: 5,
                firstName: firstName5,
                lastName: lastName5,
                contractStartDate: contractStart5,
                contractEndDate: contractEnd5,
                monthlyRent: monthlyRent5,
                unpaidMonths: this.monthDiff(contractStart5, contractEnd5),
                nextPaymentDate: this.nextPaymentDate(
                  contractStart5,
                  this.monthDiff(contractStart5, contractEnd5),
                  this.monthDiff(contractStart5, contractEnd5)
                ),
                propertyId: fullAddress + " #" + unitNumber,
                userId: auth.currentUser.uid,
                timestamp: serverTimestamp(),
              },
              {
                tenantNumber: 6,
                firstName: firstName6,
                lastName: lastName6,
                contractStartDate: contractStart6,
                contractEndDate: contractEnd6,
                monthlyRent: monthlyRent6,
                unpaidMonths: this.monthDiff(contractStart6, contractEnd6),
                nextPaymentDate: this.nextPaymentDate(
                  contractStart6,
                  this.monthDiff(contractStart6, contractEnd6),
                  this.monthDiff(contractStart6, contractEnd6)
                ),
                propertyId: fullAddress + " #" + unitNumber,
                userId: auth.currentUser.uid,
                timestamp: serverTimestamp(),
              },
              // Add more documents as needed
            ];

            // Iterate through the array and add each document to the batch
            documentsToAdd.forEach((document) => {
              const {
                tenantNumber,
                firstName,
                lastName,
                contractStartDate,
                contractEndDate,
                monthlyRent,
                unpaidMonths,
                nextPaymentDate,
                propertyId,
                userId,
                timestamp,
              } = document;

              //Only store tenants where particulars are all filled up
              if (
                firstName &&
                lastName &&
                contractStartDate &&
                contractEndDate
              ) {
                const docRef2 = doc(
                  db,
                  "Tenant",
                  propertyId + " Tenant:" + tenantNumber
                );

                batch.set(docRef2, {
                  tenantNumber: tenantNumber,
                  firstName: firstName,
                  lastName: lastName,
                  contractStartDate: contractStartDate,
                  contractEndDate: contractEndDate,
                  monthlyRent: monthlyRent,
                  unpaidMonths: unpaidMonths,
                  nextPaymentDate: nextPaymentDate,
                  propertyId: propertyId,
                  userId: userId,
                  timestamp: timestamp,
                });
              }
            });

            // Commit the batch to add all the documents
            await batch.commit();
          } catch (error) {
            console.error("Error adding documents: ", error);
          }
        }
        document.getElementById("addPropertyForm").reset();
        this.$emit("addedProperty");
      } catch (error) {
        //console.error("Error adding document: ", error);
        this.$swal.fire({
          icon: "error",
          title: "Error!",
          text: "Error adding document: " + error,
          confirmButtonColor: "#0d6efd",
        });
      }
    },
    retrieveAddress() {
      const xhr = new XMLHttpRequest();
      const postal_code = exampleInputPostalCode1.value;

      xhr.addEventListener("readystatechange", function () {
        if (this.readyState === this.DONE) {
          if (this.status === 200) {
            // If the request was successful (status code 200), you can access the response data here:
            const responseData = JSON.parse(this.responseText);
            const fullAddress = responseData.results[0].ADDRESS;
            document.getElementById("exampleInputFullAddress1").value =
              fullAddress;
          } else {
            // Handle errors here if the request was not successful
            console.error("Request failed with status: " + this.status);
          }
        }
      });

      xhr.open(
        "GET",
        "https://www.onemap.gov.sg/api/common/elastic/search?searchVal=" +
          postal_code +
          "&returnGeom=Y&getAddrDetails=Y&pageNum=1"
      );

      xhr.send(); // No need to send data in a GET request
    },
    monthDiff(start, end) {
      let dateTo = new Date(end);
      let dateFrom = new Date(start);
      return (
        dateTo.getMonth() -
        dateFrom.getMonth() +
        12 * (dateTo.getFullYear() - dateFrom.getFullYear())
      );
    },
    nextPaymentDate(startDate, totalMonths, unpaidMonths) {
      let paidMonths = totalMonths - unpaidMonths;
      let dateFrom = new Date(startDate);
      let nextDate = new Date(
        dateFrom.setMonth(dateFrom.getMonth() + paidMonths + 1)
      );
      return nextDate;
    },
  },
};
</script>

<style scoped>
.icon-align {
  vertical-align: text-bottom;
}
</style>